workflows:
  android-build:
    name: Android Build
    instance_type: mac_mini
    environment:
      node: latest
      yarn: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Android APK
        script: |
          npm run build
          npx cap sync android
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/**/*.apk
