# codemagic.yaml
workflows:
  android - workflow:
    name: Android Build Workflow
    instance_type: mac_mini
    max_build_duration: 60
    environment:
      vars:
        # 项目配置
        APP_ID: "com.example.splitscreen"
        APP_NAME: "SplitScreenApp"
        BUILD_NUMBER: $CM_BUILD_NUMBER
        # 签名配置（用于发布版本）
        KEYSTORE_FILE: "release - key.keystore"
        KEY_ALIAS: "your_key_alias"
      # 保留node配置，移除yarn相关配置
      node: latest
      # 导入环境变量（在Codemagic UI中设置）
      groups:
        - android_signing_credentials
        - android_keys
    # 其他配置部分保持不变
    cache:
      cache_paths:
        - $HOME/.npm
        - $HOME/.yarn
        - $CM_BUILD_DIR/node_modules
    scripts:
      - name: Install dependencies
        script: |
          npm install -g cordova
          npm install
      # 后续脚本配置...
    artifacts:
      - platforms/android/app/build/outputs/apk/**/*.apk
      - platforms/android/app/build/outputs/bundle/**/*.aab
    publishing:
      email:
        recipients:
          - developer@example.com
        notify:
          success: true
          failure: true
