workflows:
  android-build:
    name: Android Build & Publish
    instance_type: mac_mini
    max_build_duration: 60
    environment:
      node: 18.16.0
      yarn: 1.22.19
      vars:
        APP_ID: "com.example.splitscreen"
        APP_VERSION: "1.0.0"
        ANDROID_SDK_ROOT: $HOME/Library/Android/sdk
      groups:
        - android-credentials  # 包含签名密钥和Google Play发布凭证
        
    # 缓存依赖项以加速后续构建
    cache:
      cache_paths:
        - $HOME/.npm
        - $HOME/.yarn
        - $CM_BUILD_DIR/node_modules
        - $ANDROID_SDK_ROOT/build-tools
        - $ANDROID_SDK_ROOT/platforms
        - $ANDROID_SDK_ROOT/platform-tools
        
    scripts:
      - name: Setup environment
        script: |
          echo "Setting up environment variables..."
          export PATH="$PATH:$ANDROID_SDK_ROOT/tools/bin"
          export GRADLE_USER_HOME="$CM_BUILD_DIR/.gradle"
          
      - name: Install dependencies
        script: |
          echo "Installing project dependencies..."
          npm install -g cordova@12.0.0
          npm install
          
      - name: Configure Android SDK
        script: |
          echo "Installing Android SDK components..."
          sdkmanager --install "platforms;android-33" "build-tools;33.0.2" "cmdline-tools;latest"
          sdkmanager --licenses || true  # 自动接受许可证
          
      - name: Decode signing key
        script: |
          echo "Preparing signing key..."
          echo $KEYSTORE | base64 --decode > release.keystore
          chmod 600 release.keystore
          
      - name: Validate project configuration
        script: |
          echo "Validating project configuration..."
          cordova --version
          node --version
          npm --version
          
      - name: Build web assets
        script: |
          echo "Building web application..."
          npm run build
          
      - name: Add Android platform
        script: |
          echo "Adding Android platform..."
          cordova platform add android@12.0.0
          
      - name: Configure split-screen support
        script: |
          echo "Enabling split-screen support..."
          # 修改AndroidManifest.xml添加必要权限和特性
          sed -i -e 's/<application/<application android:resizeableActivity="true"/' platforms/android/app/src/main/AndroidManifest.xml
          
      - name: Build debug APK
        script: |
          echo "Building debug APK..."
          cordova build android --debug
          
      - name: Build release APK
        script: |
          echo "Building signed release APK..."
          cordova build android --release -- --keystore=release.keystore \
            --storePassword=$KEYSTORE_PASSWORD \
            --alias=$KEY_ALIAS \
            --password=$KEY_PASSWORD
          
      - name: Build Android App Bundle (AAB)
        script: |
          echo "Building Android App Bundle..."
          cd platforms/android
          ./gradlew bundleRelease -Pandroid.injected.signing.store.file=../release.keystore \
            -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD \
            -Pandroid.injected.signing.key.alias=$KEY_ALIAS \
            -Pandroid.injected.signing.key.password=$KEY_PASSWORD
          cd ../..
          
    artifacts:
      - platforms/android/app/build/outputs/apk/**/*.apk
      - platforms/android/app/build/outputs/bundle/**/*.aab
      - platforms/android/app/build/outputs/mapping/**/*.txt
      
    publishing:
      email:
        recipients:
          - developer@example.com
        notify:
          success: true
          failure: true
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        artifacts:
          - platforms/android/app/build/outputs/bundle/release/app-release.aab
