workflows:
  android-build:
    name: Android Build
    environment:
      flutter: stable
      java: openjdk11
      node: latest
    scripts:
      - name: Install Yarn and dependencies
        script: |
          npm install -g yarn
          flutter pub get
          yarn install
      - name: Build Android app
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/**/*.apk
