workflows:
  android - workflow:
    name: Android Build Workflow
    instance_type: mac_mini
    max_build_duration: 60
    environment:
      vars:
        APP_ID: "com.example.splitscreen"
        APP_NAME: "SplitScreenApp"
        BUILD_NUMBER: $CM_BUILD_NUMBER
        KEYSTORE_FILE: "release - key.keystore"
        KEY_ALIAS: "your_key_alias"
      node: latest
      groups:
        - android_signing_credentials
        - android_keys
    cache:
      cache_paths:
        - $HOME/.npm
        - $HOME/.yarn
        - $CM_BUILD_DIR/node_modules
    scripts:
      - name: Install dependencies
        script:
          npm install -g cordova
          npm install
    artifacts:
      - platforms/android/app/build/outputs/apk/**/*.apk
      - platforms/android/app/build/outputs/bundle/**/*.aab
    publishing:
      email:
        recipients:
          - developer@example.com
        notify:
          success: true
          failure: true
